spring:
  application.name: github-gardener

  config:
    import:
      - feign.yml
      - openai.yml
      - github.yml
  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      chat:
        options:
          model: gpt-4o-mini

github:
  username: ${github.username}
  token: ${github.token}
